postgres:
  jdbc_url: "jdbc:postgresql://food_delivery_postgres:5432/food_delivery_db"
  host: "food_delivery_postgres"
  port: 5432
  db: "food_delivery_db"
  user: "student"
  password: "student123"
  table: "2025em1100471_orders"

kafka:
  brokers: "kafka:29092"
  topic: "2025em1100471_food_orders_raw"

datalake:
  path: "/opt/spark-apps/datalake/food/2025em1100471/output/orders"
  format: "parquet"

streaming:
  checkpoint_location: "/opt/spark-apps/datalake/food/2025em1100471/checkpoints/orders"
  last_processed_timestamp_location: "/opt/spark-apps/datalake/food/2025em1100471/lastprocess/orders"
  batch_interval: 5
